export const CONFIG = {
  SCREEN_WIDTH: 1200,
  SCREEN_HEIGHT: 800,

  PARTICLE_RADIUS: 3.0,
  PARTICLE_MIN_DISTANCE: 6.0,
  MAX_PARTICLES: 4096,

  GRAVITY: 400.0,
  FRICTION: 0.8,
  BOUNCE_DAMPING: 0.25,
  RESTITUTION: 0.1,
  TANGENTIAL_DAMPING: 0.02,

  MAX_VELOCITY: 800.0,
  VELOCITY_THRESHOLD: 30.0,
  MIN_VELOCITY_FOR_COLLISION: 0.5,

  CELL_SIZE: 15.0,
  MAX_PARTICLES_PER_CELL: 256,
  COLLISION_DISTANCE_THRESHOLD: 9.0,

  SOLVER_PASSES: 1,
  SPAWN_RATE: 3,
  SLEEPING_THRESHOLD: 15,
  VELOCITY_SLEEP_THRESHOLD: 0.1,
};

export const GRID_WIDTH = Math.ceil(CONFIG.SCREEN_WIDTH / CONFIG.CELL_SIZE) + 2;
export const GRID_HEIGHT = Math.ceil(CONFIG.SCREEN_HEIGHT / CONFIG.CELL_SIZE) +
  2;
